export enum EstadoAlerta {
  PENDIENTE = 'PENDIENTE',
  EN_GESTION = 'EN_GESTION',
  RESUELTA = 'RESUELTA',
  DESCARTADA = 'DESCARTADA',
}

export enum EstadoFactura {
  PENDIENTE = 'PENDIENTE',
  PAGADA = 'PAGADA',
  PAGADA_PARCIAL = 'PAGADA_PARCIAL',
  VENCIDA = 'VENCIDA',
  ANULADA = 'ANULADA',
}

export enum EstadoMedidor {
  ACTIVO = 'ACTIVO',
  SUSPENDIDO = 'SUSPENDIDO',
  RETIRADO = 'RETIRADO',
  EN_REPARACION = 'EN_REPARACION',
}

export enum EstadoSuscriptor {
  ACTIVO = 'ACTIVO',
  SUSPENDIDO = 'SUSPENDIDO',
  CORTADO = 'CORTADO',
  RETIRADO = 'RETIRADO',
}

export enum MetodoPago {
  EFECTIVO = 'EFECTIVO',
  TRANSFERENCIA = 'TRANSFERENCIA',
  DEPOSITO_BANCARIO = 'DEPOSITO_BANCARIO',
  TARJETA_DEBITO = 'TARJETA_DEBITO',
  TARJETA_CREDITO = 'TARJETA_CREDITO',
  PAGO_MOVIL = 'PAGO_MOVIL',
}

export enum RolUsuario {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  OPERADOR = 'OPERADOR',
  CAJERO = 'CAJERO',
  CONSULTA = 'CONSULTA',
}

export enum TipoAlerta {
  CONSUMO_ANOMALO = 'CONSUMO_ANOMALO',
  MORA_VENCIDA = 'MORA_VENCIDA',
  MEDIDOR_SIN_LECTURA = 'MEDIDOR_SIN_LECTURA',
  FUGA_POSIBLE = 'FUGA_POSIBLE',
  SUSCRIPTOR_SUSPENDIDO = 'SUSCRIPTOR_SUSPENDIDO',
  MANTENIMIENTO = 'MANTENIMIENTO',
}

export enum TipoSuscriptor {
  DOMICILIAR = 'DOMICILIAR',
  COMERCIAL = 'COMERCIAL',
  INDUSTRIAL = 'INDUSTRIAL',
  INSTITUCIONAL = 'INSTITUCIONAL',
}
